### PR TITLE
Late database connection

### PR DESCRIPTION
**Pull request by guiled**
Open the connection the later we can (not at the Dal construction, but at the first connection need).

It may makes some BC break if user test the connection result on construction.

But I think it is a good practice
* The connection is not opened when a script doesn't need it
* The database resource is less occupied by script using late connection

NB: please consider this PR after #17 as I included the main commit about PHP5.4 migration

### CODE REVIEW

**Comment by Hywan** [comment]
@guiled Ping? Are you available to work on this PR? If no, I guess someone can take over it.

**Comment by Hywan** [comment]
Any volunteer to work on this PR /cc @hoaproject/hoackers?

**Comment by Hywan** [comment]
ping?

**Comment by Metalaka** [comment]
I'll look it this week.

**Comment by Hywan** [comment]
Perfect, thanks!

**Pull request closed without merging**
